rework csync and add a up-directory search for the .remoteignore file

diff --git a/csync b/csync
--- a/csync
+++ b/csync
@@ -1,97 +1,144 @@
 #!/usr/bin/bash
 
 # Script for syncing my project folders with the ones on the remote server we work on.
+# Use with:
+#   clustersync push/pull         to copy files
+#   clustersync push/pull sync    to synchronize (be careful not to lose anything)
+#   clustersync push/pull check   to check differences
 
-# use with:  clustersync push/pull         to copy files
-#            clustersync push/pull sync    to synchronize (be careful not to lose anything)
-#            clustersync push/pull check   to check differences
+# This is heavily inspired by Prof. Dr. Leandro Martinez's script (https://github.com/lmiq/tips/blob/master/GoogleDrive/gdrive)
+# You can also create a .remoteignore file to exclude any file from syncing.
 
-# This is heavily inspired in the following script by Prof. Dr. Leandro Martinez (https://github.com/lmiq/tips/blob/master/GoogleDrive/gdrive)
-# You can also create a file .remoteignore (such as a .gitignore file) to exclude any file from syncing
+usage() {
+  echo "Usage: $0 [remote] [action] [sync/check] [options]"
+  echo
+  echo "Arguments:"
+  echo "  remote       The remote server to sync with: newton, jupiter, or pipeline."
+  echo "  action       The action to perform: push or pull."
+  echo "  sync/check   (optional) Synchronize the files or check for differences."
+  echo
+  echo "Options:"
+  echo "  -n, --no-ignore   Do not use .remoteignore files."
+  echo "  -h, --help        Show this help message."
+  exit 1
+}
 
-# Change your local and remote working directories here.
+use_ignore=true
 
-if [[ "$1" == "newton" ]] ; then
-  remote="newton"
-  projects=$NEWTON_PROJECTS
-elif [[ "$1" == "jupiter" ]] ; then
-  remote="jupiter"
-  projects=$JUPITER_PROJECTS
-elif [[ "$1" == "pipeline" ]] ; then
-  remote="pipeline"
-  projects=$LOCAL_PROJECTS
-else
-  echo "ERROR: First argument must be 'newton', 'pipeline' or 'jupiter'"
-  exit
+# Parse options and arguments
+while [[ $# -gt 0 ]]; do
+  case "$1" in
+    -h|--help)
+      usage
+      ;;
+    -n|--no-ignore)
+      use_ignore=false
+      shift
+      ;;
+    newton|jupiter|pipeline)
+      remote="$1"
+      case "$remote" in
+        newton)
+          projects=$NEWTON_PROJECTS
+          ;;
+        jupiter)
+          projects=$JUPITER_PROJECTS
+          ;;
+        pipeline)
+          projects=$LOCAL_PROJECTS
+          ;;
+        *)
+          echo "ERROR: Invalid remote '$1'. Must be 'newton', 'jupiter', or 'pipeline'."
+          usage
+          ;;
+      esac
+      shift
+      ;;
+    push|pull)
+      action="$1"
+      shift
+      ;;
+    sync|check)
+      sync_check="$1"
+      shift
+      ;;
+    *)
+      echo "ERROR: Unknown argument '$1'."
+      usage
+      ;;
+  esac
+done
+
+# Ensure required arguments are provided
+if [[ -z "$remote" || -z "$action" ]]; then
+  echo "ERROR: Missing required arguments."
+  usage
 fi
 
-current_dir=`pwd`'/'
-echo "Current directory: $current_dir"
+# Set up directories
+current_dir=$(pwd)'/'
 
-# check if current folder is a subfolder of the local directory defined above:
-
-if [[ "$current_dir" == "$LOCAL_PROJECTS"* ]] ; then
-
-  echo "Current dir is a $remote subfolder"
-  
+if [[ "$current_dir" == "$LOCAL_PROJECTS"* ]]; then
   len_local=${#LOCAL_PROJECTS}
   len_current=${#current_dir}
   remote_dir=${current_dir:$len_local:$len_current}
-  target=$remote:$projects$remote_dir
-  
-  # set the correct folders
-  current_local=$current_dir
-  current_remote=$target"/"
-
-else 
-
-  echo "Current dir is NOT a $remote subfolder. Quitting."
-  exit
-
-fi
-
-ignore_files=`find .remoteignore 2>/dev/null`
-
-# check for files to ignore
-
-if [[ $ignore_files ]]; then
-  echo '.remoteignore found, ignoring the files listed'
-  ignore_fullpath=`pwd`/.remoteignore
-  ignore_flag="--exclude-from $ignore_fullpath" 
+  target="$remote:$projects$remote_dir"
+  current_local="$current_dir"
+  current_remote="$target"
 else
-  echo 'No .remoteignore file found.' 
-  ignore_flag=""
+  echo "Current dir is NOT a $remote subfolder. Quitting."
+  exit 1
 fi
 
+# Function to find .remoteignore file up to the home directory
+find_remoteignore() {
+  local dir="$current_dir"
+  while [[ "$dir" != "$HOME" && "$dir" != "/" ]]; do
+    if [[ -f "$dir/.remoteignore" ]]; then
+      echo "$dir/.remoteignore"
+      return
+    fi
+    dir=$(dirname "$dir")
+  done
+  return 1
+}
 
-# Push, pull
+# Check for .remoteignore file
+ignore_flag=""
+if [[ "$use_ignore" == true ]]; then
+  ignore_files=$(find_remoteignore)
+  if [[ $ignore_files ]]; then
+    echo ".remoteignore found at $ignore_files, ignoring the files listed"
+    ignore_flag="--exclude-from $ignore_files"
+  else
+    echo "No .remoteignore file found."
+  fi
+else
+  echo "Ignoring .remoteignore file is deactivated."
+fi
 
-if [[ "$2" == "push" ]] ; then
+# Set up rsync source/destination
+if [[ "$action" == "push" ]]; then
   source="$current_local"
   destination="$current_remote"
-elif [[ "$2" == "pull" ]] ; then
+elif [[ "$action" == "pull" ]]; then
   source="$current_remote"
   destination="$current_local"
 else
-  echo "ERROR: Second argument must be 'push', 'pull'"
-  exit
+  echo "ERROR: Second argument must be 'push' or 'pull'"
+  exit 1
 fi
 
-# Sync, check
-
+# Handle sync/check options
 last_flag=""
-
-if [[ "$3" == "sync" ]] ; then
-  last_flag=--delete
-elif [[ "$3" == "check" ]] ; then
-  last_flag=--dry-run
-elif [[ "$3" > " " ]] ; then
-  echo "ERROR: Third argument, if any, must be 'sync', 'check'"
-  exit
+if [[ "$sync_check" == "sync" ]]; then
+  last_flag="--delete"
+elif [[ "$sync_check" == "check" ]]; then
+  last_flag="--dry-run"
 fi
 
-ssh $1 "mkdir -p $projects$remote_dir"
+# Ensure target directory exists on the remote server
+ssh "$remote" "mkdir -p $projects$remote_dir"
 
-rsync -rtvuc $ignore_flag $last_flag $source $destination
-
-
+# Run rsync command
+rsync -rtvuc $ignore_flag $last_flag "$source" "$destination"
